### ISSUE TITLE
rescan: update filter fetching interfaces to allow for batch filter fetching

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/neutrino#68]
The finalized version of `BIP 157` [allows nodes to query for a _batch_ of filters in a single message](https://github.com/lightninglabs/neutrino/blob/36d9a509ff4ea1e916a73c6f1c2b784c1faf11ed/query.go#L319). This is useful as if we're catching up from a few thousand blocks, we can request them all in a _single_ message, and get the responses pipelined, rather than the back and forth of repeatedly fetching _each_ filter individually. 

Currently, this isn't exposed to the caller, nor utilized internally for rescan (or `GetUtxo`) purposes.

# Steps To Completion 

- [ ] Modify the `GetCfilters` method to expose both a start height and stop hash just as in the p2p message. To start with, one can convert all the existing calls to use the height of the filter to be requested, and use the stop hash of that very same header. 

- [ ] Where relevant ([in the rescan loop for example](https://github.com/lightninglabs/neutrino/blob/master/rescan.go#L288)) start fetching filters in batch, rather than fetching them individually. One way to do this is at the top of the loop we can check if our starting height is very far behind the height of the main node. If so, we can likely fetch the filters using a single batch query.

- [ ] Update the `GetUTXO` method to also fetch the filters in batch. This is likely where we'll see an even bigger savings as outside of the regular rescan loop, we may be starting far-ish in the past. 

The above changes will likely also affect `btcsuite/btcwallet` and a similar set of optimizations during it's initial chain sync, and also the HD seed import rescan can take advantage of this optimization.

**Comment by rawtxapp** [comment]
This looks straightforward, I'd like to try to do it if no one is working on it.

If yes, what do you think of using a "predicted cache" inside `GetCFilter`, so something like:
- if filter 50 is requested, the function could fetch filters 30-to-70 or possibly checkpoint-to-checkpoint and store them in a cache inside itself, so that on the next call to it, it could return immediately, presumably the marginal cost of fetching extra filters is very low.
- if the caller wants the flexibility, it could use queryoptions to set start height and stop hash, or it could potentially just hint towards which direction it's scanning and let GetCFilter take care of caching (for example: I'm scanning backwards, give me filter 50, GetCFilter would fetch filters 20-to-50).

That way, the logic in the callers wouldn't need to change and GetCFilter could try different batch sizes to optimize network/CPU/memory. But you know better, what do you think ?

**Comment by Roasbeef** [comment]
> This looks straightforward, I'd like to try to do it if no one is working on it.

Note that this PR will span 3 repos (including `neutrino`). 

> If yes, what do you think of using a "predicted cache" inside GetCFilter, so something like:

Let's just get the basic functionality down before doing anything fancy.

**Comment by losh11** [comment]
Has there been any work done to this? My application uses neutrino for syncing, and getting cfilters for a wallet that's two years old takes over an hour on my iPhone 13 Pro, which makes neutrino syncing painful for the avg user.
