### ISSUE TITLE
Writes to headerStore not ACID

### ISSUE THREAD

**Issue by ChrisSchinnerl** [lightninglabs/neutrino#93]
Hi, I just took a look at the `headerStore` and noticed that you use [`appendRaw`](https://github.com/lightninglabs/neutrino/blob/166fe699d5964581d24e6bfff0aa329cfb6a8bc9/headerfs/file.go#L12) for writing headers atomically. Seems like the actual transaction to disk is not ACID though which could lead to corrupted writes to the store in some situations.
If that's a concern you could check out our [writeaheadlog](https://gitlab.com/NebulousLabs/writeaheadlog) implementation which we came up with due to the need of writing all kinds of metadata rapidly and in an ACID way.
If you like it I could also create a PR.

**Comment by cfromknecht** [comment]
Thanks for the report @ChrisSchinnerl, can you be more specific about which ACID components are lacking and why they’re required for this use case? What scenarios do you have in mind?

Idt full compliance is required in this situation, though I’m interested in hearing your thoughts on how it can be improved

**Comment by ChrisSchinnerl** [comment]
Oh I just realized that the `headerStore` is append-only which means a write-ahead-log might be overkill since it doesn't need to be ACID.
The main scenario I had in mind would be a a sudden shutdown due to losing power in which case the operating system wouldn't be able to flush its buffer for the file to disk. Of course it varies between operating systems, but usually there is no guarantee that data is persisted correctly unless a call to `file.Sync` returned without errors.
A power outage could then potentially cause headers which were written to be missing after a crash (which is probably not an issue) or in the worse case cause the end of the file to be corrupted. The result of that would be a parsing error when reading headers at the end of the file (or in the middle if the corruption remains undetected) and/or a file size that is no longer a multiple of the `headerSize`.

**Comment by cfromknecht** [comment]
> Oh I just realized that the `headerStore` is append-only which means a write-ahead-log might be overkill since it doesn't need to be ACID.

Indeed

On restart we trim the file to ensure that it is a multiple of `headerSize` to handle this case. We aren’t specifically concerned if the batch isn’t committed atomically either, as well just resync from the last full header. In that sense, we are only concerned with the atomicity of each `headerSize` segment. 

In general, our usage is append only, though we do have cases where we rewind to handle reorgs. However, since we only have one writer, isolation isn’t really an issue either.

It could be worth adding a sync call on shutdown to ensure all buffers are flushed, though I’m not sure if it’s required for every write if the proper recovery measures are in place. I’m guessing the performance hit would be non-neglible if done on every `appendRaw`, so avoiding that is preferable.

The possibility of disk corruption is of course something we’d like to avoid, though some more research here would help determine the extent to which that is possible and/or tolerable given our restricted usage patterns and looser requirements.

**Comment by ChrisSchinnerl** [comment]
I agree, syncing on every call could be a significant performance hit. For Sia we currently use bbolt to store blocks which basically syncs after every block and it is definitely something we struggle with.

> On restart we trim the file to ensure that it is a multiple of headerSize to handle this case.
Ah I missed that. That should probably work just fine for unfinished writes. I think once you trimmed the file to the correct length, you could simply read the last header and trim it too if you can't decode it, until the last header is one that you can decode. 
We are currently operating under the assumption that a crash can only corrupt a single physical sector on disk since each of them should be written atomically. We also assume that a physical sector is at least 4kib large on the average modern drive. For your use case that should mean that only the end of the file could be corrupted.
